
#include <sifteo.h>
#include "phonemic.h"
#include "word_families.h"

#define WORD(w) {&ChunkSound_##w, &ChunkImage_##w}

WordFamily wordFamilies[] = {
	/* can write quick script to create this structure from our original dictionary format */
   {/* Level 0 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 1 */
		{	/*word*/
			WORD(baby),
			WORD(boat),
			WORD(box),
			WORD(boy),
			WORD(bread),
			WORD(cake),
			WORD(cat),
			WORD(chair),
		},
		{	/*word length*/
			4,3,3,3,4,3,3,3,
		},
		{	/*grapheme*/
			{"b","a","b","y"},
			{"b","oa","t"},
			{"b","o","x"},
			{"b","o","y"},
			{"b","r","ea","d"},
			{"c","a","ke"},
			{"c","a","t"},
			{"ch","ai","r"},
		},
		{	/*phoneme*/
			{PHON(b),PHON(aa),PHON(b),PHON(ee)},
			{PHON(b),PHON(oo),PHON(t)},
			{PHON(b),PHON(o),PHON(x)},
			{PHON(b),PHON(o),PHON(y)},
			{PHON(b),PHON(r),PHON(e),PHON(d)},
			{PHON(k),PHON(aa),PHON(k)},
			{PHON(c),PHON(a),PHON(t)},
			{PHON(ch),PHON(e),PHON(r)},
		},
	},
	{/* Level 2 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 3 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 4 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 5 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 6 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 7 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
};