
#include <sifteo.h>
#include "phonemic.h"
#include "word_families.h"

#define WORD(w) {&ChunkSound_##w, &ChunkImage_##w}

WordFamily wordFamilies[] = {
	/* can write quick script to create this structure from our original dictionary format */
   {/* Level 0 */
		{	/*word*/
			WORD(apple),
			WORD(back),
			WORD(ball),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,3,3,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"a","pp","le"},
			{"b","a","ck"},
			{"b","a","ll"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(a),PHON(p),PHON(l)},
			{PHON(b),PHON(a),PHON(k)},
			{PHON(b),PHON(o),PHON(l)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
	{/* Level 1 */
		{	/*word*/
			WORD(baby),
			WORD(boat),
			WORD(box),
			WORD(boy),
			WORD(bread),
			WORD(cake),
			WORD(cat),
			WORD(chair),
		},
		{	/*word length*/
			4,3,4,3,4,3,3,3,
		},
		{	/*grapheme*/
			{"b","a","b","y"},
			{"b","oa","t"},
			{"b","o","x",""},
			{"b","o","y"},
			{"b","r","ea","d"},
			{"c","a","ke"},
			{"c","a","t"},
			{"ch","ai","r"},
		},
		{	/*phoneme*/
			{PHON(b),PHON(aa),PHON(b),PHON(ee)},
			{PHON(b),PHON(oo),PHON(t)},
			{PHON(b),PHON(o),PHON(k),PHON(s)},
			{PHON(b),PHON(oo),PHON(ee)},
			{PHON(b),PHON(r),PHON(e),PHON(d)},
			{PHON(k),PHON(aa),PHON(k)},
			{PHON(k),PHON(a),PHON(t)},
			{PHON(ch),PHON(e),PHON(r)},
		},
	},
	{/* Level 2 */
		{	/*word*/
			WORD(chicken),
			WORD(coat),
			WORD(corn),
			WORD(cow),
			WORD(dog),
			WORD(doll),
			WORD(door),
			WORD(duck),
		},
		{	/*word length*/
			4,3,4,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"ch","i","ck","en"},
			{"c","oa","t"},
			{"c","o","r","n"},
			{"c","o","w"},
			{"d","o","g"},
			{"d","o","ll"},
			{"d","oo","r"},
			{"d","u","ck"},
		},
		{	/*phoneme*/
			{PHON(ch),PHON(i),PHON(k),PHON(n)},
			{PHON(k),PHON(oo),PHON(t)},
			{PHON(k),PHON(oo),PHON(r),PHON(n)},
			{PHON(k),PHON(o),PHON(w)},
			{PHON(d),PHON(o),PHON(g)},
			{PHON(d),PHON(o),PHON(l)},
			{PHON(d),PHON(oo),PHON(r)},
			{PHON(d),PHON(u),PHON(k)},
		},
	},
	{/* Level 3 */
		{	/*word*/
			WORD(egg),
			WORD(eye),
			WORD(farm),
			WORD(feet),
			WORD(fire),
			WORD(fish),
			WORD(flower),
			WORD(garden),
		},
		{	/*word length*/
			2,1,4,3,3,3,5,5,
		},
		{	/*grapheme*/
			{"e","gg"},
			{"eye"},
			{"f","a","r","m"},
			{"f","ee","t"},
			{"f","i","re"},
			{"f","i","sh"},
			{"f","l","o","w","er"},
			{"g","a","r","d","en"},
		},
		{	/*phoneme*/
			{PHON(e),PHON(g)},
			{PHON(ii)},
			{PHON(f),PHON(o),PHON(r),PHON(m)},
			{PHON(f),PHON(ee),PHON(t)},
			{PHON(f),PHON(ii),PHON(r)},
			{PHON(f),PHON(i),PHON(sh)},
			{PHON(f),PHON(l),PHON(o),PHON(w),PHON(r)},
			{PHON(g),PHON(o),PHON(r),PHON(d),PHON(n)},
		},
	},
	{/* Level 4 */
		{	/*word*/
			WORD(girl),
			WORD(grass),
			WORD(hand),
			WORD(head),
			WORD(hill),
			WORD(home),
			WORD(horse),
			WORD(milk),
		},
		{	/*word length*/
			3,4,4,3,3,3,4,4,
		},
		{	/*grapheme*/
			{"g","ir","l"},
			{"g","r","a","ss"},
			{"h","a","n","d"},
			{"h","ea","d"},
			{"h","i","ll"},
			{"h","o","me"},
			{"h","o","r","se"},
			{"m","i","l","k"},
		},
		{	/*phoneme*/
			{PHON(g),PHON(r),PHON(l)},
			{PHON(g),PHON(r),PHON(a),PHON(s)},
			{PHON(h),PHON(a),PHON(n),PHON(d)},
			{PHON(h),PHON(e),PHON(d)},
			{PHON(h),PHON(i),PHON(l)},
			{PHON(h),PHON(oo),PHON(m)},
			{PHON(h),PHON(oo),PHON(r),PHON(s)},
			{PHON(m),PHON(i),PHON(l),PHON(k)},
		},
	},
	{/* Level 5 */
		{	/*word*/
			WORD(money),
			WORD(nest),
			WORD(paper),
			WORD(pig),
			WORD(rabbit),
			WORD(rain),
			WORD(ring),
			WORD(santa_claus),
		},
		{	/*word length*/
			4,4,4,3,5,3,4,9,
		},
		{	/*grapheme*/
			{"m","o","n","ey"},
			{"n","e","s","t"},
			{"p","a","p","er"},
			{"p","i","g"},
			{"r","a","bb","i","t"},
			{"r","ai","n"},
			{"r","i","n","g"},
			{"s","a","n","t","a","c","l","au","se"},
		},
		{	/*phoneme*/
			{PHON(m),PHON(u),PHON(n),PHON(ee)},
			{PHON(n),PHON(e),PHON(s),PHON(t)},
			{PHON(p),PHON(aa),PHON(p),PHON(r)},
			{PHON(p),PHON(i),PHON(g)},
			{PHON(r),PHON(a),PHON(b),PHON(i),PHON(t)},
			{PHON(r),PHON(aa),PHON(n)},
			{PHON(r),PHON(ee),PHON(n),PHON(g)},
			{PHON(s),PHON(a),PHON(n),PHON(t),PHON(u),PHON(k),PHON(l),PHON(o),PHON(s)},
		},
	},
	{/* Level 6 */
		{	/*word*/
			WORD(sheep),
			WORD(shoe),
			WORD(squirrel),
			WORD(sun),
			WORD(table),
			WORD(time),
			WORD(tree),
			WORD(watch),
		},
		{	/*word length*/
			3,2,4,3,4,3,3,3,
		},
		{	/*grapheme*/
			{"sh","ee","p"},
			{"sh","oe"},
			{"s","qu","irr","el"},
			{"s","u","n"},
			{"t","a","b","le"},
			{"t","i","me"},
			{"t","r","ee"},
			{"w","a","tch"},
		},
		{	/*phoneme*/
			{PHON(sh),PHON(ee),PHON(p)},
			{PHON(sh),PHON(uu)},
			{PHON(s),PHON(kw),PHON(r),PHON(l)},
			{PHON(s),PHON(u),PHON(n)},
			{PHON(t),PHON(aa),PHON(b),PHON(l)},
			{PHON(t),PHON(ii),PHON(m)},
			{PHON(t),PHON(r),PHON(ee)},
			{PHON(w),PHON(o),PHON(ch)},
		},
	},
	{/* Level 7 */
		{	/*word*/
			WORD(wood),
			WORD(water),
			WORD(window),
			WORD(bear),
			WORD(bed),
			WORD(bell),
			WORD(bird),
			WORD(car),
		},
		{	/*word length*/
			3,4,5,3,3,3,3,3,
		},
		{	/*grapheme*/
			{"w","oo","d"},
			{"w","a","t","er"},
			{"w","i","n","d","ow"},
			{"b","ea","r"},
			{"b","e","d"},
			{"b","e","ll"},
			{"b","ir","d"},
			{"c","a","r"},
		},
		{	/*phoneme*/
			{PHON(w),PHON(u),PHON(d)},
			{PHON(w),PHON(o),PHON(t),PHON(r)},
			{PHON(w),PHON(i),PHON(n),PHON(d),PHON(oo)},
			{PHON(b),PHON(e),PHON(r)},
			{PHON(b),PHON(e),PHON(d)},
			{PHON(b),PHON(e),PHON(l)},
			{PHON(b),PHON(r),PHON(d)},
			{PHON(k),PHON(o),PHON(r)},
		},
	},
};